In [1]:
import pandas as pd

In [2]:
ugm =  pd.read_csv("dataset/etd_ugm.csv")
usk =  pd.read_csv("dataset/etd_usk.csv")
kompas =  pd.read_csv("dataset/kompas.csv")
mojok =  pd.read_csv("dataset/mojok.csv")
tempo =  pd.read_csv("dataset/tempo.csv")
dataset = [ugm, usk, kompas, mojok, tempo]

In [3]:
for data in dataset:
    print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   judul   10000 non-null  object
 1   konten  10000 non-null  object
dtypes: object(2)
memory usage: 156.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   judul   10000 non-null  object
 1   konten  10000 non-null  object
dtypes: object(2)
memory usage: 156.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   judul   10000 non-null  object
 1   konten  10000 non-null  object
dtypes: object(2)
memory usage: 156.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9484 entries, 0 to 9483
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   judul   9484 non-null   object
 1   konten  9484 non-null   object
dtypes: object(2)
memory usage: 148.3+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   judul   10000 non-null  object
 1   konten  10000 non-null  object
dtypes: object(2)
memory usage: 156.4+ KB
None

In [4]:
for data in dataset:
    data['judul'] = data['judul'].str.strip()
    data['konten'] = data['konten'].str.strip()
    data['judul'] = data['judul'].astype('string')
    data['konten'] = data['konten'].astype('string')

In [5]:
for data in dataset:
    print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   judul   10000 non-null  string
 1   konten  10000 non-null  string
dtypes: string(2)
memory usage: 156.4 KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   judul   10000 non-null  string
 1   konten  10000 non-null  string
dtypes: string(2)
memory usage: 156.4 KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   judul   10000 non-null  string
 1   konten  10000 non-null  string
dtypes: string(2)
memory usage: 156.4 KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9484 entries, 0 to 9483
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   judul   9484 non-null   string
 1   konten  9484 non-null   string
dtypes: string(2)
memory usage: 148.3 KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   judul   10000 non-null  string
 1   konten  10000 non-null  string
dtypes: string(2)
memory usage: 156.4 KB
None

In [6]:
for i in dataset:
    print(i.head(15))
    print("\n")

                                                judul  \
0   Peningkatan Penggunaan Serangan Drone dalam Pe...
1   PREDIKSI HARGA APARTEMEN DENGAN MEMPERTIMBANGK...
2   EFEK PEMBERIAN PROGRAM PENURUNAN BERAT BADAN B...
3   MOBILE BANKING USAGE INTENTION ANALYSIS IN IND...
4   Estimasi Volume Tegakan Menggunakan Pemodelan ...
5   Peran Efikasi Diri Terhadap Motivasi Kerja pad...
6   Analisis Potensi Peningkatan Kapasitas Beban d...
7   Kehidupan Tunawisma dalam Novel Mukhayyalah al...
8   Townhouse dengan Pendekatan New Urbanism di Ko...
9   A Comparison Between Linear Regression and Neu...
10  Dunia Virtual sebagai Dunia Penuh Kemungkinan ...
11  Proyeksi Deforestasi dan Dampaknya Terhadap Ha...
12  Estimasi Suplai Magma dan Sumber Tekanan Gunun...
13  A Corpus-Based Study of Writer Identities in B...
14  Analisis Frekuensi Mikronukleus Sel Epitel Muk...

                                               konten
0   Drone secara umum dapat diklasifikasikan sebag...
1   Properti di Indonesia saat ini merupakan bentu...
2   Latar Belakang : Obesitas merupakan salah satu...
3   Pemulihan ekonomi global pada tahun 2022 yang ...
4   Pendugaan volume\r\ntegakan merupakan proses p...
5   Abstrak. Salah satu sumber daya yang berperan ...
6   Solar tracker merupakan sebuah alat yang dapat...
7   Tujuan dari penelitian ini adalah mengungkapka...
8   Kota Tangerang Selatan merupakan kota yang per...
9   Prediksi hasil teh adalah teknik untuk mempred...
10  Dunia virtual, sebuah dunia yang di dalamnya m...
11  Koridor Katingan-Kahayan saat ini merupakan sa...
12  Gunung Merapi adalah salah satu gunung berapi ...
13  Penulisan ilmiah, khususnya artikel penelitian...
14  Down syndromemerupakan kelainan genetik yang t...


                                                judul  \
0   PEMAHAMAN KONSEP DAN MOTIVASI PESERTA DIDIK SM...
1   TINJAUAN HUKUM PEMBUKTIAN KASUS TINDAK PIDANA ...
2   PENGARUH KESESUAIAN INDIVIDU-ORGANISASI DAN KE...
3   PENGARUH PERKEMBANGAN INFRASTRUKTUR EKONOMI DA...
4   PENERAPAN METODE REDUKSI VARIABEL DALAM MENYEL...
5   HUBUNGAN ANTARA MINDFULNESS DENGAN KECEMASAN A...
6   RASIONALITAS JANJI POLITIK AMINULLAH USMAN TER...
7   ANALISIS PERAN DINAS KESEHATAN DALAM PENGAWASA...
8   GAMBARAN SITOLOGI ULAS VAGINA KUDA LOKAL YANG ...
9   PENERAPAN MODEL DISCOVERY LEARNING BERBANTUAN ...
10  PENGARUH PERSEPSI NILAI DAN KEPUASAN WISATAWAN...
11  PENGGUNAAN SAPAAN KEKERABATAN DALAM BAHASA DEV...
12  PENGARUH MODEL PEMBELAJARAN TALKING CHIPS  TER...
13  ETNOFARMASI UNTUK MENINGKATKAN IMUNITAS PADA M...
14  DNA BARCODING ENAM JENIS TANAMAN OBAT SUKU ZIN...

                                               konten
0   Dewi Agustiani (2018). Pemahaman Konsep dan Mo...
1   Sanksi terhadap tindak pidana korupsi oleh mer...
2   ABSTRAKPenelitian ini bertujuan untuk mengukur...
3   Penelitian ini bertujuan untuk melihat pengaru...
4   Masalah perencanaan produksi adalah salah satu...
5   ABSTRAKKecemasan akan kematian adalah kondisi ...
6   ABSTRAKPada masa kampanye Aminullah Usman tahu...
7   ABSTRAKAir bersih yang layak minum, merupakan ...
8   Salah satu teknik untuk mendiagnosis gangguan ...
9   Firaq Akbar. (2024). Penerapan Model Discovery...
10  Penelitian ini bertujuan untuk menguji pengaru...
11  ABSTRAKAnjeli, Silviana. 2023. Penggunaan Sapa...
12  ABSTRAKJannah, Khairatul. 2022. Pengaruh Model...
13  Erni Sartifa, Erni. 2021. Etnofarmasi Untuk Me...
14  ABSTRAKSalah satu kelompok tanaman yang sering...


                                                judul  \
0   Xiaomi Rilis Mijia Smart Audio Glasses 2, Kaca...
1   Saham Apple, Amazon, Nvidia Melonjak Serentak,...
2   Modus Pencabulan Berkedok Pengobatan di Bekasi...
3   Dampak Penggunaan Obat Antibiotik Berulang pad...
4               Begini Cara Urus Sertifikat Apartemen
5   Pemerintah Klaim Beras Surplus dan Ingin Ekspo...
6   5 Manfaat Media Monitoring Bisnis, Salah Tahun...
7   Posko Ormas di Matraman Jadi Pos Kamling, Warg...
8   Cek Jadwal dan Lokasi SIM Keliling di Jakarta ...
9   Mulai 15 Mei 2025 Ada Penyesuaian Tarif Jalan ...
10  5 Cara Usir Lalat Buah Pakai Bahan Dapur, Tanp...
11  Serunya Memacu Adrenalin di River Tubing Pusur...
12  Siapa yang Membayar Pecalang, Petugas Keamanan...
13  Truk TNI Bermuatan Amunisi Meledak di Tol Gemp...
14  Como Kehilangan Assane Diao, Fabregas Tak Perl...

                                               konten
0   KOMPAS.com - Xiaomi mengumumkan kacamata pinta...
1   JAKARTA, KOMPAS.com – Saham teknologi raksasa ...
2   BEKASI, KOMPAS.com - Polres Metro Bekasi Kota ...
3   KOMPAS.com - Penggunaan obat antibiotik telah ...
4   JAKARTA, KOMPAS.com - Masyarakat yang membeli ...
5   JAKARTA, KOMPAS.com – Pemerintah sedang menyia...
6   KOMPAS.com - Sudahkah kamu melakukan media mon...
7   JAKARTA, KOMPAS.com - Pengalihan fungsi sejuml...
8   JAKARTA, KOMPAS.com - Polda Metro Jaya membuka...
9   KOMPAS.com – Tarif jalan tol Kunciran-Serpong ...
10  KOMPAS.com - Lalat buah sering kali muncul di ...
11  KOMPAS.com – Kali atau Sungai Pusur yang membe...
12  KOMPAS.com - Kehadiran organisasi masyarakat (...
13  KOMPAS.com - Sebuah truk milik Kostrad yang me...
14  KOMPAS.com - Como 1907, yang dimiliki oleh pen...


                                                judul  \
0   7 Lagu Anime yang Pasti Bikin Kamu Makin Semangat
1   Dilema Penduduk Ketapang: Dominasi Lion Air ya...
2   5 Hal yang Tidak Boleh Dilakukan Pengendara Mo...
3   Ironi Situbondo: Kotanya Sepi, Bupatinya Jadi ...
4   User Experience: MacBook Air dan Pro Masih Ala...
5   Meluruskan Salah Kaprah Terkait IAHN Gde Pudja...
6   Boga Group Rekrut Lansia Bekerja, Tampar Perus...
7   Jembatan Aborsi, Contoh Nyata Beratnya Perjuan...
8   Ikut Organisasi Mahasiswa Itu Sah-sah Saja, as...
9   Cerita Tukang Fotokopi Jadi Saksi Mahasiswa UG...
10        5 Pertanyaan yang Membuat Orang Jogja Kesal
11         Ketiduran di Kuburan karena Ulah Ojol Gaib
12  Perempuan, Makhluk yang Punya Banyak Alasan un...
13  Anak Muda Butuh Olimpiade Indonesia Cerdas, Ac...
14  Hal-hal yang Perlu Diluruskan tentang GKB Gres...

                                               konten
0   Lagu anime punya magis tersendiri. Ia tidak di...
1   Mencari tiket penerbangan pulang dari Jakarta ...
2   Berkendara di Indonesia memang selalu penuh ta...
3   Situbondo, tempat kelahiran yang begitu tenang...
4   MOJOK.CO – Mau kerja santai, bisa pakai MacBoo...
5   Perguruan tinggi Hindu negeri banyak berada di...
6   Umur hanyalah angka, sebab menurunnya kapasita...
7   Mahasiswa UI yang nggak bawa kendaraan ke kamp...
8   Menjadi mahasiswa merupakan waktu yang tepat u...
9   Tempat fotokopi 24 jam adalah penolong para ma...
10  Jogja (baca: Yogyakarta) bukan daerah yang asi...
11  MOJOK.CO – Saya kaget setelah menyadari pengem...
12  Banyak teman perempuan saya mengeluh mengenai ...
13  Pemerintah wajib menghidupkan lagi acara TV Ol...
14  Ketika tengah membaca beberapa artikel di Term...


                                                judul  \
0   United Airlines Terbakar Usai Kelinci Terhisap...
1   Liburan ke Jepang Tanpa Izin, Wamendagri: Bupa...
2   Polda Aceh: Laporkan Siapa pun yang Mengaku Bi...
3   Tim Bulu Tangkis Indonesia Gagal ke Final Pial...
4   Mengenal Sindrom Piring Bersih, Pantang Berhen...
5   500 Ribu Orang Diprediksi ke Banyuwangi selama...
6   Sekolah Rakyat Butuh 8 Hektare Lahan untuk Men...
7   Kapolri Listyo Sigit Sebut Terjadi Peningkatan...
8   Kemenkes Imbau Jemaah Haji Gunakan Masker untu...
9   Ketika Tentara dan Polisi yang Hendak Menjual ...
10     Saham FORE Mulai Melantai di Bursa Senin Besok
11  Direktur Penyelidikan KPK Endar Priantoro Dimu...
12  Prabowo Dijadwalkan Pidato di Parlemen Turkiye...
13  Eks Anggota Kompolnas: Pembahasan RUU Polri Ha...
14  Polda Lampung Ungkap Kasus Premanisme Gangster...

                                               konten
0   TEMPO.CO,Jakarta- Sebuah pesawatUnited Airline...
1   TEMPO.CO,Jakarta- Wakil Menteri Dalam Negeri a...
2   TEMPO.CO,Jakarta- Kabid HumasPolda AcehKombes ...
3   Pebulu tangkis ganda campuran Indonesia Dejan ...
4   TEMPO.CO,Jakarta- Banyak orang merasa tak nyam...
5   TEMPO.CO,Banyuwangi-Banyuwangidiperkirakan bak...
6   TEMPO.CO,Jakarta- Menteri SosialSaifullah Yusu...
7   TEMPO.CO,Jakarta-Kapolri Jenderal Listyo Sigit...
8   TEMPO.CO,Jakarta- Kementerian Kesehatan mengim...
9   TEMPO.CO,Medan- Operasi gabungan dari Balai Pe...
10  TEMPO.CO,Jakarta-Saham emiten gerai kopi PT Fo...
11  TEMPO.CO,Jakarta- Direktur Penyelidikan KPKEnd...
12  TEMPO.CO,Jakarta- PresidenPrabowoSubianto tiba...
13  TEMPO.CO,Jakarta- Mantan anggota Komisi Kepoli...
14  TEMPO.CO,Jakarta- Kepolisian Daerah MetroLampu...

1. Membuat Lower Case
2. Menghilangkan non-alphanumeric

In [7]:
import re

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', ' ', text) 
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [8]:
source_names = ['etd-ugm', 'etd-usk', 'kompas', 'tempo', 'mojok']

for data, source in zip(dataset, source_names):
    data['source'] = source
    print(f"Mulai preprocessing {source}...")
    
    data['konten_clean'] = data['konten'].apply(preprocess_text)
    data['judul_clean'] = data['judul'].apply(preprocess_text)
    
    print(f"✅ {source} selesai diproses.")

Mulai preprocessing etd-ugm...
✅ etd-ugm selesai diproses.
Mulai preprocessing etd-usk...
✅ etd-usk selesai diproses.
Mulai preprocessing kompas...
✅ kompas selesai diproses.
Mulai preprocessing tempo...
✅ tempo selesai diproses.
Mulai preprocessing mojok...
✅ mojok selesai diproses.

1. Handling Individual

In [9]:
#1. usk
#masing banyak kata 'abstrak' yang terselip di konten 
usk['konten_clean'] = usk['konten_clean'].str.replace(r'\babstrak(?=[a-z0-9])', ' ', regex=True)
usk['konten_clean'] = usk['konten_clean'].str.replace(r'\babstrak\b', ' ', regex=True)
usk['konten_clean'] = usk['konten_clean'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [10]:
usk

,judul,konten,source,konten_clean,judul_clean
0,PEMAHAMAN KONSEP DAN MOTIVASI PESERTA DIDIK SM...,Dewi Agustiani (2018). Pemahaman Konsep dan Mo...,etd-usk,dewi agustiani 2018 pemahaman konsep dan motiv...,pemahaman konsep dan motivasi peserta didik sm...
1,TINJAUAN HUKUM PEMBUKTIAN KASUS TINDAK PIDANA ...,Sanksi terhadap tindak pidana korupsi oleh mer...,etd-usk,sanksi terhadap tindak pidana korupsi oleh mer...,tinjauan hukum pembuktian kasus tindak pidana ...
2,PENGARUH KESESUAIAN INDIVIDU-ORGANISASI DAN KE...,ABSTRAKPenelitian ini bertujuan untuk mengukur...,etd-usk,penelitian ini bertujuan untuk mengukur pengar...,pengaruh kesesuaian individu organisasi dan ke...
3,PENGARUH PERKEMBANGAN INFRASTRUKTUR EKONOMI DA...,Penelitian ini bertujuan untuk melihat pengaru...,etd-usk,penelitian ini bertujuan untuk melihat pengaru...,pengaruh perkembangan infrastruktur ekonomi da...
4,PENERAPAN METODE REDUKSI VARIABEL DALAM MENYEL...,Masalah perencanaan produksi adalah salah satu...,etd-usk,masalah perencanaan produksi adalah salah satu...,penerapan metode reduksi variabel dalam menyel...
...,...,...,...,...,...
9995,PENERAPAN MODEL PEMBELAJARAN KOOPERATIF TIPE R...,ABSTRAKModel pembelajaran reciprocal teaching ...,etd-usk,model pembelajaran reciprocal teaching adalah ...,penerapan model pembelajaran kooperatif tipe r...
9996,PERBUATAN MELAWAN HUKUM OLEH PPAT DALAM PENERB...,PERBUATAN MELAWAN HUKUM OLEH PPAT DALAM PENERB...,etd-usk,perbuatan melawan hukum oleh ppat dalam penerb...,perbuatan melawan hukum oleh ppat dalam penerb...
9997,ANALISIS KETERAMPILAN BERMAIN BULUTANGKIS ATLE...,"ABSTRAKHaikal, Muhammad. (2022). Analisis Kete...",etd-usk,haikal muhammad 2022 analisis keterampilan ber...,analisis keterampilan bermain bulutangkis atle...
9998,ANALISIS TINGKAT KESESUAIAN INFORMASI LAPORAN ...,ABSTRAKPertumbuhan Usaha Mikro Kecil dan Menen...,etd-usk,pertumbuhan usaha mikro kecil dan menengah umk...,analisis tingkat kesesuaian informasi laporan ...
9999,ANALISIS STABILITAS TEBING SUNGAI ALAS MENGGUN...,"AbstrakSungai dapat menjadi sumber air bersih,...",etd-usk,sungai dapat menjadi sumber air bersih pengger...,analisis stabilitas tebing sungai alas menggun...

In [11]:
usk = usk.drop(columns=["judul", "konten", "source"])

In [12]:
usk = usk.rename(columns={"konten_clean": "konten", "judul_clean": "judul"})

In [13]:
usk

,konten,judul
0,dewi agustiani 2018 pemahaman konsep dan motiv...,pemahaman konsep dan motivasi peserta didik sm...
1,sanksi terhadap tindak pidana korupsi oleh mer...,tinjauan hukum pembuktian kasus tindak pidana ...
2,penelitian ini bertujuan untuk mengukur pengar...,pengaruh kesesuaian individu organisasi dan ke...
3,penelitian ini bertujuan untuk melihat pengaru...,pengaruh perkembangan infrastruktur ekonomi da...
4,masalah perencanaan produksi adalah salah satu...,penerapan metode reduksi variabel dalam menyel...
...,...,...
9995,model pembelajaran reciprocal teaching adalah ...,penerapan model pembelajaran kooperatif tipe r...
9996,perbuatan melawan hukum oleh ppat dalam penerb...,perbuatan melawan hukum oleh ppat dalam penerb...
9997,haikal muhammad 2022 analisis keterampilan ber...,analisis keterampilan bermain bulutangkis atle...
9998,pertumbuhan usaha mikro kecil dan menengah umk...,analisis tingkat kesesuaian informasi laporan ...
9999,sungai dapat menjadi sumber air bersih pengger...,analisis stabilitas tebing sungai alas menggun...

In [14]:
#2 Kompas
#masing banyak kata 'kompas.com' yang terselip di konten
kompas['konten_clean'] = kompas['konten_clean'].str.replace(r'\bkompas\s*com\b', ' ', regex=True)
kompas['konten_clean'] = kompas['konten_clean'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [15]:
kompas

,judul,konten,source,konten_clean,judul_clean
0,"Xiaomi Rilis Mijia Smart Audio Glasses 2, Kaca...",KOMPAS.com - Xiaomi mengumumkan kacamata pinta...,kompas,xiaomi mengumumkan kacamata pintar terbaru mij...,xiaomi rilis mijia smart audio glasses 2 kacam...
1,"Saham Apple, Amazon, Nvidia Melonjak Serentak,...","JAKARTA, KOMPAS.com – Saham teknologi raksasa ...",kompas,jakarta saham teknologi raksasa as yang tergab...,saham apple amazon nvidia melonjak serentak ma...
2,Modus Pencabulan Berkedok Pengobatan di Bekasi...,"BEKASI, KOMPAS.com - Polres Metro Bekasi Kota ...",kompas,bekasi polres metro bekasi kota menangkap murt...,modus pencabulan berkedok pengobatan di bekasi...
3,Dampak Penggunaan Obat Antibiotik Berulang pad...,KOMPAS.com - Penggunaan obat antibiotik telah ...,kompas,penggunaan obat antibiotik telah umum digunaka...,dampak penggunaan obat antibiotik berulang pad...
4,Begini Cara Urus Sertifikat Apartemen,"JAKARTA, KOMPAS.com - Masyarakat yang membeli ...",kompas,jakarta masyarakat yang membeli unit hunian di...,begini cara urus sertifikat apartemen
...,...,...,...,...,...
9995,Vidio Perpanjang Hak Siar Premier League hingg...,KOMPAS.com - Vidio resmi memperpanjang kontrak...,kompas,vidio resmi memperpanjang kontrak eksklusif de...,vidio perpanjang hak siar premier league hingg...
9996,Pesawat F-16 Milik Ukraina Jatuh Saat Mengadan...,KOMPAS.com - Ukraina kembali kehilangan satu p...,kompas,ukraina kembali kehilangan satu pesawat tempur...,pesawat f 16 milik ukraina jatuh saat mengadan...
9997,"Jejak Gedung Sarinah, Warisan Soekarno yang Pe...","JAKARTA, KOMPAS.com – Di tengah hiruk-pikuk ka...",kompas,jakarta di tengah hiruk pikuk kawasan thamrin ...,jejak gedung sarinah warisan soekarno yang per...
9998,"KemenKopUKM Dipisah, Posisi LPDB-KUMKM Belum A...","SUBANG, KOMPAS.com - Direktur Utama Lembaga Pe...",kompas,subang direktur utama lembaga pengelola dana b...,kemenkopukm dipisah posisi lpdb kumkm belum ad...
9999,"Mengenal Sejarah Lokal: Pengertian, Sumber, da...",KOMPAS.com - Pernahkah kamu membaca tentang ko...,kompas,pernahkah kamu membaca tentang konflik sampit ...,mengenal sejarah lokal pengertian sumber dan c...

In [16]:
kompas = kompas.drop(columns=["judul", "konten", "source"])
kompas = kompas.rename(columns={"konten_clean": "konten", "judul_clean": "judul"})

In [17]:
kompas

,konten,judul
0,xiaomi mengumumkan kacamata pintar terbaru mij...,xiaomi rilis mijia smart audio glasses 2 kacam...
1,jakarta saham teknologi raksasa as yang tergab...,saham apple amazon nvidia melonjak serentak ma...
2,bekasi polres metro bekasi kota menangkap murt...,modus pencabulan berkedok pengobatan di bekasi...
3,penggunaan obat antibiotik telah umum digunaka...,dampak penggunaan obat antibiotik berulang pad...
4,jakarta masyarakat yang membeli unit hunian di...,begini cara urus sertifikat apartemen
...,...,...
9995,vidio resmi memperpanjang kontrak eksklusif de...,vidio perpanjang hak siar premier league hingg...
9996,ukraina kembali kehilangan satu pesawat tempur...,pesawat f 16 milik ukraina jatuh saat mengadan...
9997,jakarta di tengah hiruk pikuk kawasan thamrin ...,jejak gedung sarinah warisan soekarno yang per...
9998,subang direktur utama lembaga pengelola dana b...,kemenkopukm dipisah posisi lpdb kumkm belum ad...
9999,pernahkah kamu membaca tentang konflik sampit ...,mengenal sejarah lokal pengertian sumber dan c...

In [18]:
#3 tempo
tempo['konten_clean'] = tempo['konten_clean'].str.replace(r'\btempo\s*co\b', ' ', regex=True)
tempo['konten_clean'] = tempo['konten_clean'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [19]:
tempo = tempo.drop(columns=['judul', 'konten', 'source'])
tempo = tempo.rename(columns={"konten_clean": "konten", "judul_clean": "judul"})

In [20]:
tempo

,konten,judul
0,jakarta sebuah pesawatunited airlinesmendarat ...,united airlines terbakar usai kelinci terhisap...
1,jakarta wakil menteri dalam negeri atau wamend...,liburan ke jepang tanpa izin wamendagri bupati...
2,jakarta kabid humaspolda acehkombes joko krisd...,polda aceh laporkan siapa pun yang mengaku bis...
3,pebulu tangkis ganda campuran indonesia dejan ...,tim bulu tangkis indonesia gagal ke final pial...
4,jakarta banyak orang merasa tak nyaman bila ti...,mengenal sindrom piring bersih pantang berhent...
...,...,...
9995,jakarta ketua komisi xii dpr ri bambang patija...,dpr minta pemerintah jaga stabilitas pasokan g...
9996,tradisi bakar batu perayaan pelantikan jhon ta...,tradisi bakar batu simbol solidaritas masyarak...
9997,jakarta aplikasicek pbb online memudahkan masy...,ragam platform dan aplikasi untuk cek tagihan ...
9998,wonogiri seorang wisatawan asal jakarta mengal...,wisatawan gagal mendarat saat menjajal wisata ...
9999,hubungan indonesia dan arab saudi terus menunj...,menag indonesia dapat perhatian khusus dari ar...

In [21]:
#4 mojok
mojok['konten_clean'] = mojok['konten_clean'].str.replace(r'\bmojok\s*co\b', ' ', regex=True)
mojok['konten_clean'] = mojok['konten_clean'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [22]:
mojok = mojok.drop(columns=['judul', 'konten', 'source'])
mojok = mojok.rename(columns={"konten_clean": "konten", "judul_clean": "judul"})

In [23]:
mojok

,konten,judul
0,lagu anime punya magis tersendiri ia tidak dib...,7 lagu anime yang pasti bikin kamu makin semangat
1,mencari tiket penerbangan pulang dari jakarta ...,dilema penduduk ketapang dominasi lion air yan...
2,berkendara di indonesia memang selalu penuh ta...,5 hal yang tidak boleh dilakukan pengendara mo...
3,situbondo tempat kelahiran yang begitu tenang ...,ironi situbondo kotanya sepi bupatinya jadi te...
4,mau kerja santai bisa pakai macbook air mau ke...,user experience macbook air dan pro masih alat...
...,...,...
9479,pantai marina semarang bukanlah tempat biasa i...,pantai marina semarang tempat ospek mahasiswa ...
9480,jalan tunjungan surabaya bisa dibilang adalah ...,jalan tunjungan surabaya tempat wisata overrat...
9481,purwokerto terkenal sebagai kota dengan biaya ...,biaya hidup murah mahasiswa purwokerto tetap n...
9482,tidak sedikit pada sarjana eksakta ataupun sos...,jangan jadi peneliti di indonesia
9483,tidak jarang kita menemui warung madura yang b...,3 rahasia yang buat warung madura nekat jualan...

In [24]:
#5 ugm
ugm = ugm.drop(columns=['judul', 'konten', 'source'])
ugm = ugm.rename(columns={"konten_clean": "konten", "judul_clean": "judul"})

In [25]:
ugm

,konten,judul
0,drone secara umum dapat diklasifikasikan sebag...,peningkatan penggunaan serangan drone dalam pe...
1,properti di indonesia saat ini merupakan bentu...,prediksi harga apartemen dengan mempertimbangk...
2,latar belakang obesitas merupakan salah satu m...,efek pemberian program penurunan berat badan b...
3,pemulihan ekonomi global pada tahun 2022 yang ...,mobile banking usage intention analysis in ind...
4,pendugaan volume tegakan merupakan proses peng...,estimasi volume tegakan menggunakan pemodelan ...
...,...,...
9995,peningkatan kebutuhan akan produk hewani di in...,pengaruh body condition score bcs induk terhad...
9996,liquid petroleum gas lpg merupakan salah satu ...,tugas akhir optimasi struktur fondasi tiang pa...
9997,maggot hermetia illucens adalah larva dari lal...,efektivitas ekstrak maggot hermetia illucens s...
9998,pemeriksaan radiografis menggunakan teknik rad...,perbandingan diagnosis karies proksimal dengan...
9999,tujuan dari penelitian ini adalah untuk mengan...,pengaruh tanggung jawab sosial pt kilang perta...

In [26]:
dataset_clean = [ugm, usk, mojok, tempo, kompas]

In [ ]:
def tokenize_text(text):
    if pd.isna(text):
        return []
    tokens = text.split()
    return tokens

if 'konten' in data.columns and 'judul' in data.columns:
    data['konten_tokens'] = data['konten'].apply(tokenize_text)
    data['judul_tokens'] = data['judul'].apply(tokenize_text)

for df in dataset_clean:
    kont_col = 'konten' if 'konten' in df.columns else 'konten'
    jud_col = 'judul' if 'judul' in df.columns else 'judul'
    df['konten_tokens'] = df[kont_col].apply(tokenize_text)
    df['judul_tokens'] = df[jud_col].apply(tokenize_text)

In [ ]:
import pandas as pd

def hitung_jumlah_kata(dataset_list, dataset_names):
    """
    Menghitung jumlah kata total dan rata-rata per dataset.
    
    Params:
    - dataset_list: list of DataFrame, misalnya [ugm, usk, mojok, tempo, kompas]
    - dataset_names: list of str, misalnya ['ugm', 'usk', 'mojok', 'tempo', 'kompas']
    
    Return:
    - DataFrame ringkasan jumlah kata
    """
    hasil = []

    for name, df in zip(dataset_names, dataset_list):
        # pastikan kolom tersedia
        if 'konten_tokens' not in df.columns or 'judul_tokens' not in df.columns:
            raise ValueError(f"Dataset {name} tidak memiliki kolom konten_tokens atau judul_tokens")
        
        # hitung jumlah kata di tiap baris
        df['konten_len'] = df['konten_tokens'].apply(lambda x: len(x) if isinstance(x, list) else 0)
        df['judul_len'] = df['judul_tokens'].apply(lambda x: len(x) if isinstance(x, list) else 0)
        
        total_konten = df['konten_len'].sum()
        total_judul = df['judul_len'].sum()
        total_semua = total_konten + total_judul
        
        rata2_konten = df['konten_len'].mean()
        rata2_judul = df['judul_len'].mean()

        hasil.append({
            'dataset': name,
            'total_konten_words': total_konten,
            'total_judul_words': total_judul,
            'total_semua_words': total_semua,
            'rata2_konten_per_dokumen': rata2_konten,
            'rata2_judul_per_dokumen': rata2_judul,
            'jumlah_dokumen': len(df)
        })

    return pd.DataFrame(hasil)

In [29]:
dataset_clean = [ugm, usk, mojok, tempo, kompas]
dataset_names = ['UGM', 'USK', 'Mojok', 'Tempo', 'Kompas']

hasil_kata = hitung_jumlah_kata(dataset_clean, dataset_names)
print(hasil_kata)

  dataset  total_konten_words  total_judul_words  total_semua_words  \
0     UGM             2376071             157212            2533283
1     USK             2114783             160570            2275353
2   Mojok             7746514             115646            7862160
3   Tempo             4012804             102533            4115337
4  Kompas             3129328             100916            3230244

   rata2_konten_per_dokumen  rata2_judul_per_dokumen  jumlah_dokumen
0                237.607100                  15.7212           10000
1                211.478300                  16.0570           10000
2                816.798186                  12.1938            9484
3                401.280400                  10.2533           10000
4                312.932800                  10.0916           10000

In [36]:
import pandas as pd

def combine_datasets_keep_cols(dataset_list, dataset_names,
                               cols_tokens=('konten_tokens','judul_tokens'),
                               cols_len=('konten_len','judul_len'),
                               source_col='source'):
    """
    Gabungkan beberapa DataFrame dan hasilkan DataFrame yang hanya berisi:
      konten_tokens, judul_tokens, konten_len, judul_len, source

    Params:
      dataset_list : list of DataFrame [ugm, usk, ...]
      dataset_names: list of nama sumber ['UGM','USK',...]
    Return:
      combined_df : pandas DataFrame gabungan dengan kolom yang diminta
    """
    if len(dataset_list) != len(dataset_names):
        raise ValueError("dataset_list dan dataset_names harus sama panjang")

    dfs = []
    for df, name in zip(dataset_list, dataset_names):
        df_copy = df.copy()

        # pastikan kolom token ada; jika belum, buat kolom kosong atau tokenisasi
        for tcol in cols_tokens:
            if tcol not in df_copy.columns:
                # jika tidak ketemu, buat kolom kosong list agar tidak error
                df_copy[tcol] = [[] for _ in range(len(df_copy))]

        # pastikan kolom panjang ada; jika tidak, hitung dari token list
        if cols_len[0] not in df_copy.columns:
            df_copy[cols_len[0]] = df_copy[cols_tokens[0]].apply(lambda x: len(x) if isinstance(x, list) else 0)
        if cols_len[1] not in df_copy.columns:
            df_copy[cols_len[1]] = df_copy[cols_tokens[1]].apply(lambda x: len(x) if isinstance(x, list) else 0)

        # tambahkan kolom source (label)
        df_copy[source_col] = name

        # pilih hanya kolom yang diperlukan
        keep_cols = [cols_tokens[0], cols_tokens[1], cols_len[0], cols_len[1], source_col]
        # pastikan kolom urut
        df_copy = df_copy.reindex(columns=keep_cols)

        dfs.append(df_copy)

    # gabungkan semuanya
    combined_df = pd.concat(dfs, ignore_index=True, sort=False)
    return combined_df

# =======================
# Contoh pemakaian
# =======================
dataset_clean = [ugm, usk, mojok, tempo, kompas]
dataset_names = ['UGM', 'USK', 'Mojok', 'Tempo', 'Kompas']

combined = combine_datasets_keep_cols(dataset_clean, dataset_names)
print(combined.shape)
print(combined.head())

(49484, 5)
                                       konten_tokens  \
0  [drone, secara, umum, dapat, diklasifikasikan,...
1  [properti, di, indonesia, saat, ini, merupakan...
2  [latar, belakang, obesitas, merupakan, salah, ...
3  [pemulihan, ekonomi, global, pada, tahun, 2022...
4  [pendugaan, volume, tegakan, merupakan, proses...

                                        judul_tokens  konten_len  judul_len  \
0  [peningkatan, penggunaan, serangan, drone, dal...         240         15
1  [prediksi, harga, apartemen, dengan, mempertim...         239         14
2  [efek, pemberian, program, penurunan, berat, b...         393         21
3  [mobile, banking, usage, intention, analysis, ...         178         16
4  [estimasi, volume, tegakan, menggunakan, pemod...         383         24

  source
0    UGM
1    UGM
2    UGM
3    UGM
4    UGM

In [37]:
combined

,konten_tokens,judul_tokens,konten_len,judul_len,source
0,"[drone, secara, umum, dapat, diklasifikasikan,...","[peningkatan, penggunaan, serangan, drone, dal...",240,15,UGM
1,"[properti, di, indonesia, saat, ini, merupakan...","[prediksi, harga, apartemen, dengan, mempertim...",239,14,UGM
2,"[latar, belakang, obesitas, merupakan, salah, ...","[efek, pemberian, program, penurunan, berat, b...",393,21,UGM
3,"[pemulihan, ekonomi, global, pada, tahun, 2022...","[mobile, banking, usage, intention, analysis, ...",178,16,UGM
4,"[pendugaan, volume, tegakan, merupakan, proses...","[estimasi, volume, tegakan, menggunakan, pemod...",383,24,UGM
...,...,...,...,...,...
49479,"[vidio, resmi, memperpanjang, kontrak, eksklus...","[vidio, perpanjang, hak, siar, premier, league...",421,10,Kompas
49480,"[ukraina, kembali, kehilangan, satu, pesawat, ...","[pesawat, f, 16, milik, ukraina, jatuh, saat, ...",317,10,Kompas
49481,"[jakarta, di, tengah, hiruk, pikuk, kawasan, t...","[jejak, gedung, sarinah, warisan, soekarno, ya...",349,10,Kompas
49482,"[subang, direktur, utama, lembaga, pengelola, ...","[kemenkopukm, dipisah, posisi, lpdb, kumkm, be...",499,8,Kompas
49483,"[pernahkah, kamu, membaca, tentang, konflik, s...","[mengenal, sejarah, lokal, pengertian, sumber,...",336,7,Kompas

In [43]:


from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

factory = StopWordRemoverFactory()
global_stopwords = set(factory.get_stop_words())

def remove_stopwords(tokens, stopwords):
    return [word for word in tokens if word not in stopwords]

combined['konten_tokens'] = combined['konten_tokens'].apply(lambda x: remove_stopwords(x, global_stopwords))
combined['judul_tokens'] = combined['judul_tokens'].apply(lambda x: remove_stopwords(x, global_stopwords))

combined['konten_len'] = combined['konten_tokens'].apply(len)
combined['judul_len'] = combined['judul_tokens'].apply(len)

print(combined.head())

                                       konten_tokens  \
0  [drone, umum, diklasifikasikan, semua, kendara...
1  [properti, indonesia, merupakan, bentuk, inves...
2  [latar, belakang, obesitas, merupakan, salah, ...
3  [pemulihan, ekonomi, global, tahun, 2022, mend...
4  [pendugaan, volume, tegakan, merupakan, proses...

                                        judul_tokens  konten_len  judul_len  \
0  [peningkatan, penggunaan, serangan, drone, per...         173         12
1  [prediksi, harga, apartemen, mempertimbangkan,...         166         11
2  [efek, pemberian, program, penurunan, berat, b...         303         17
3  [mobile, banking, usage, intention, analysis, ...         141         16
4  [estimasi, volume, tegakan, menggunakan, pemod...         299         23

  source
0    UGM
1    UGM
2    UGM
3    UGM
4    UGM

In [44]:
combined

,konten_tokens,judul_tokens,konten_len,judul_len,source
0,"[drone, umum, diklasifikasikan, semua, kendara...","[peningkatan, penggunaan, serangan, drone, per...",173,12,UGM
1,"[properti, indonesia, merupakan, bentuk, inves...","[prediksi, harga, apartemen, mempertimbangkan,...",166,11,UGM
2,"[latar, belakang, obesitas, merupakan, salah, ...","[efek, pemberian, program, penurunan, berat, b...",303,17,UGM
3,"[pemulihan, ekonomi, global, tahun, 2022, mend...","[mobile, banking, usage, intention, analysis, ...",141,16,UGM
4,"[pendugaan, volume, tegakan, merupakan, proses...","[estimasi, volume, tegakan, menggunakan, pemod...",299,23,UGM
...,...,...,...,...,...
49479,"[vidio, resmi, memperpanjang, kontrak, eksklus...","[vidio, perpanjang, hak, siar, premier, league...",334,10,Kompas
49480,"[ukraina, kehilangan, satu, pesawat, tempur, f...","[pesawat, f, 16, milik, ukraina, jatuh, mengad...",246,9,Kompas
49481,"[jakarta, tengah, hiruk, pikuk, kawasan, thamr...","[jejak, gedung, sarinah, warisan, soekarno, pe...",270,9,Kompas
49482,"[subang, direktur, utama, lembaga, pengelola, ...","[kemenkopukm, dipisah, posisi, lpdb, kumkm, ke...",353,6,Kompas
49483,"[pernahkah, kamu, membaca, konflik, sampit, te...","[mengenal, sejarah, lokal, pengertian, sumber,...",232,6,Kompas

In [ ]:
import os
import pickle
from tqdm import tqdm
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

def stem_tokens_list(tokens, stemmer):
    """Stem satu list token; jika bukan list, kembalikan list kosong."""
    if not isinstance(tokens, list):
        return []
    return [stemmer.stem(t) for t in tokens]

def stem_dataframe_in_chunks(df,
                             konten_col='konten_tokens',
                             judul_col='judul_tokens',
                             chunk_size=5000,
                             save_path=None,
                             inplace=True,
                             start_chunk=0):
   
    # init stemmer factory (bikin per proses agar thread-safe)
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()
    
    n = len(df)
    n_chunks = (n + chunk_size - 1) // chunk_size
    os.makedirs(save_path, exist_ok=True) if save_path else None

    target_cols = []
    if inplace:
        target_cols = [konten_col, judul_col]
    else:
        target_cols = [f"{konten_col}_stem", f"{judul_col}_stem"]
        # init new cols empty
        df[target_cols[0]] = [[] for _ in range(n)]
        df[target_cols[1]] = [[] for _ in range(n)]

    for chunk_idx in tqdm(range(start_chunk, n_chunks), desc="Stemming chunks"):
        i0 = chunk_idx * chunk_size
        i1 = min(n, (chunk_idx + 1) * chunk_size)
        # slice view
        slice_idx = range(i0, i1)

        # apply stemming on konten
        for col, out_col in [(konten_col, target_cols[0]), (judul_col, target_cols[1])]:
            # process rows in slice
            # local stemmer instance used already (Sastrawi Stemmer object reused safely here)
            for ridx in slice_idx:
                toks = df.at[ridx, col] if col in df.columns else []
                # guard for non-list
                if not isinstance(toks, list):
                    res = []
                else:
                    # faster list comprehension
                    res = [stemmer.stem(t) for t in toks]
                df.at[ridx, out_col] = res

        if save_path:
            fname = os.path.join(save_path, f"stem_checkpoint_chunk_{chunk_idx:04d}.pkl")
            with open(fname, 'wb') as f:
                pickle.dump({'chunk_idx': chunk_idx, 'i0': i0, 'i1': i1, 'df_slice': df.iloc[i0:i1]}, f)
    return df

In [51]:

combined_df = stem_dataframe_in_chunks(
    combined,
    konten_col='konten_tokens',
    judul_col='judul_tokens',
    chunk_size=1000,            
    save_path='checkpoints_stem',
    inplace=True
)

Stemming chunks: 100%|██████████| 50/50 [5:00:02<00:00, 360.05s/it]

In [2]:
import pandas as pd

In [7]:
df = pd.read_pickle('checkpoints_stem/stem_checkpoint_chunk_0000.pkl')['df_slice']

In [12]:
import os
import re

checkpoint_dir = 'checkpoints_stem'
if not os.path.isdir(checkpoint_dir):
    print(f"Directory not found: {checkpoint_dir}")
else:
    files = []
    for fn in os.listdir(checkpoint_dir):
        m = re.match(r'stem_checkpoint_chunk_(\d{4})\.pkl$', fn)
        if m:
            files.append((int(m.group(1)), os.path.join(checkpoint_dir, fn)))
    files.sort()

    dfs = []
    for idx, fpath in files:
        try:
            df_slice = pd.read_pickle(fpath)['df_slice']
            dfs.append(df_slice)
            print(f"Loaded chunk {idx:04d}: shape {df_slice.shape}")
        except Exception as e:
            print(f"Failed to load {fpath}: {e}")

    if dfs:
        df_all = pd.concat(dfs, ignore_index=True, sort=False)
    else:
        df_all = pd.DataFrame()

    print("Combined dataframe shape:", df_all.shape)
    print(df_all.head())

Loaded chunk 0000: shape (1000, 5)
Loaded chunk 0001: shape (1000, 5)
Loaded chunk 0002: shape (1000, 5)
Loaded chunk 0003: shape (1000, 5)
Loaded chunk 0004: shape (1000, 5)
Loaded chunk 0005: shape (1000, 5)
Loaded chunk 0006: shape (1000, 5)
Loaded chunk 0007: shape (1000, 5)
Loaded chunk 0008: shape (1000, 5)
Loaded chunk 0009: shape (1000, 5)
Loaded chunk 0010: shape (1000, 5)
Loaded chunk 0011: shape (1000, 5)
Loaded chunk 0012: shape (1000, 5)
Loaded chunk 0013: shape (1000, 5)
Loaded chunk 0014: shape (1000, 5)
Loaded chunk 0015: shape (1000, 5)
Loaded chunk 0016: shape (1000, 5)
Loaded chunk 0017: shape (1000, 5)
Loaded chunk 0018: shape (1000, 5)
Loaded chunk 0019: shape (1000, 5)
Loaded chunk 0020: shape (1000, 5)
Loaded chunk 0021: shape (1000, 5)
Loaded chunk 0022: shape (1000, 5)
Loaded chunk 0023: shape (1000, 5)
Loaded chunk 0024: shape (1000, 5)
Loaded chunk 0025: shape (1000, 5)
Loaded chunk 0026: shape (1000, 5)
Loaded chunk 0027: shape (1000, 5)
Loaded chunk 0028: shape (1000, 5)
Loaded chunk 0029: shape (1000, 5)
Loaded chunk 0030: shape (1000, 5)
Loaded chunk 0031: shape (1000, 5)
Loaded chunk 0032: shape (1000, 5)
Loaded chunk 0033: shape (1000, 5)
Loaded chunk 0034: shape (1000, 5)
Loaded chunk 0035: shape (1000, 5)
Loaded chunk 0036: shape (1000, 5)
Loaded chunk 0037: shape (1000, 5)
Loaded chunk 0038: shape (1000, 5)
Loaded chunk 0039: shape (1000, 5)
Loaded chunk 0040: shape (1000, 5)
Loaded chunk 0041: shape (1000, 5)
Loaded chunk 0042: shape (1000, 5)
Loaded chunk 0043: shape (1000, 5)
Loaded chunk 0044: shape (1000, 5)
Loaded chunk 0045: shape (1000, 5)
Loaded chunk 0046: shape (1000, 5)
Loaded chunk 0047: shape (1000, 5)
Loaded chunk 0048: shape (1000, 5)
Loaded chunk 0049: shape (484, 5)
Combined dataframe shape: (49484, 5)
                                       konten_tokens  \
0  [drone, umum, klasifikasi, semua, kendara, bai...
1  [properti, indonesia, rupa, bentuk, investasi,...
2  [latar, belakang, obesitas, rupa, salah, satu,...
3  [pulih, ekonomi, global, tahun, 2022, dapat, m...
4  [duga, volume, tega, rupa, proses, ukur, volum...

                                        judul_tokens  konten_len  judul_len  \
0  [tingkat, guna, serang, drone, perang, lawan, ...         173         12
1  [prediksi, harga, apartemen, timbang, faktor, ...         166         11
2  [efek, beri, program, turun, berat, badan, bas...         303         17
3  [mobile, banking, usage, intention, analysis, ...         141         16
4  [estimasi, volume, tega, guna, model, empiris,...         299         23

  source
0    UGM
1    UGM
2    UGM
3    UGM
4    UGM

In [19]:
df_all['source'].value_counts()

source
UGM       10000
USK       10000
Tempo     10000
Kompas    10000
Mojok      9484
Name: count, dtype: int64